server:
  #端口port
  port: 2090
spring:
  application:
    name: edu-vr-service
    # 资源信息
    messages:
      # 国际化资源文件路径
      basename: i18n/messages
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  #  datasource:
  #    dynamic:
  #      primary: master #默认首选数据源
  #      datasource:
  #        master:
  #          url: jdbc:mysql://192.168.92.2:3398/eep?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  #          username: testa
  #          password: 123456
  #          driverClassName: com.mysql.cj.jdbc.Driver
  #        slaveWgt:
  #          url: jdbc:mysql://192.168.92.2:3398/eep?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  #          username: testa
  #          password: 123456
  #          driverClassName: com.mysql.cj.jdbc.Driver
  #    type: com.zaxxer.hikari.HikariDataSource
  #    hikari:
  #      minimum-idle: 3
  #      maximum-pool-size: 20
  #      idle-timeout: 500000
  #      max-lifetime: 540000
  #      connection-timeout: 60000
  #      connection-test-query: SELECT 1
  #      data-source-properties:
  #        useSSL: false
  #        serverTimezone: Asia/Shanghai
  #        useUnicode: true
  #        characterEncoding: utf-8
  # 文件上传
  cloud:
    nacos:
      #      username: root
      #      password: mynacos
      service: ${spring.application.name}
      config:
        server-addr: localhost:8848
        group: edu
        file-extension: yaml
        namespace: test
        extension-configs[0]:
          data-id: edu-vr-db.yaml
          group: edu
      discovery:
        # 本地开发启动的服务不进行注册
        register-enabled: true
        server-addr: localhost:8848
        group: edu
        namespace: dev
    redis:
      redisson:
        file: classpath:redisson-${spring.profiles.active}.yaml
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  # 热部署
  devtools:
    restart:
      enabled: false
# 日志配置
logging:
  config: classpath:logback-spring.xml
#mybatis:
#  mapper-locations: classpath:com/zhejianglab/edu/service/vr/mapper/**/*Mapper.xml
#  configuration:
#    map-underscore-to-camel-case: true
## MyBatis
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.dojoy.epp
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mapper/mybatis-config.xml
## PageHelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql



