server:
  #端口port
  port: 2090
spring:
  application:
    name: edu-vr-service
    # 资源信息
    messages:
      # 国际化资源文件路径
      basename: i18n/messages
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.160.56.69:3360/edu_big_screen?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zghzbckj2021+++
    # Hikari 连接池配置
    # 最小空闲连接数量
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # 文件上传
  cloud:
    nacos:
      #      username: root
      #      password: mynacos
      service: ${spring.application.name}
      config:
        server-addr: localhost:8848
        group: edu
        file-extension: yaml
        namespace: test
        extension-configs[0]:
          data-id: edu-vr-db.yaml
          group: edu
      discovery:
        # 本地开发启动的服务不进行注册
        register-enabled: true
        server-addr: localhost:8848
        group: edu
        namespace: dev
    redis:
      redisson:
        file: classpath:redisson-${spring.profiles.active}.yaml
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  # 热部署
  devtools:
    restart:
      enabled: false
# 日志配置
logging:
  config: classpath:logback-spring.xml
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zhejianglab.edu
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mapper/mybatis-config.xml




